name: Compile Executable Projects
on: [push, pull_request]

jobs:
  compile:
    name: Compile Executable Projects
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current repository state
      uses: actions/checkout@v2

    - name: Set up JDK14
      uses: actions/setup-java@v1
      with:
        java-version: "14"
        java-package: jdk
        architecture: x64

    - name: Find folders with Main.java; Compile all .java files inside
      run: |
        files=$(find ./*/ -type f -name "Main.java")
        for file in $files; do
          folderpath=${file%/*}
          echo "Compiling $folderpath/..."
          javac $folderpath/*
          echo "Done"
          echo
        done
